### ISSUE TITLE
要望: ArrayQuery<T>.each(q: Query<T> => boolean | Error) が欲しいです

### ISSUE THREAD

**Issue by marihachi** [syuilo/cafy#10]
個人的な要望になります。
今書いてるプログラムで、`ArrayQuery<string>`なクエリの全ての項目に対して、ある配列の要素のどれかと一致しているかを検証したい場面があり、
```ts
arrayQuery.each(i => ['hoge', 'piyo'].indexOf(i) != -1)); // arrayQueryはArrayQuery<string>型
```
のように書いていたのですが
```ts
arrayQuery.each(q => q.or(['hoge', 'piyo'])) // arrayQueryはArrayQuery<string>型
```
のようにかけたら幸せなので、
`ArrayQuery<T>.each(q: Query<T> => boolean | Error)`
のようなAPIが欲しいと思いました。
しかしこれには、各種Queryのジェネリック化と.each()への破壊的変更が必須だと思うので、無理ならば構いません。。

使い始めたばかりで、もしかしたら的外れな事を言っているかもしれませんが、検討をお願いします。

**Comment by syuilo** [comment]
[入れ子](https://github.com/syuilo/cafy#cafyの入れ子)を駆使してもこの問題は解決しないですか？

**Comment by syuilo** [comment]
``` javascript
arrayQuery.each($().string().or(['hoge', 'piyo']))
```

**Comment by syuilo** [comment]
あー意味を理解した

**Comment by syuilo** [comment]
やってみる

**Comment by syuilo** [comment]
`eachQ`とかいう名前で新しく作れば破壊的変更は回避できそうだけどどうかな？

**Comment by marihachi** [comment]
よさそう

**Comment by marihachi** [comment]
確かに
```ts
$(x).array().each($().string().or(['hoge', 'piyo']))
```
でもいいですね。
でも、出来ればクエリの使い回しがしたかったので提案しました

**Comment by syuilo** [comment]
例で挙げていただいたコードの `q.or` した戻り値は `boolean | Error` ではなく `Query<string>` なので `ArrayQuery<T>.eachQ(q: Query<T> => Query<T>)` になる(?)

**Comment by marihachi** [comment]
あー！ そうですね

**Comment by marihachi** [comment]
(詳しい所まで分かってなくて、割りと適当なことを言っています)

**Comment by syuilo** [comment]
あーこれは型定義の観点から難しいかもしれない

**Comment by marihachi** [comment]
そうなの？

**Comment by syuilo** [comment]
ArrayQueryのeachQは、<T>によってStringQueryかNumberQueryかなどを**(型的に)**振り分けて渡す必要がある

**Comment by syuilo** [comment]
つまり `Query<T>`ではなくて、`StringQuery | NumberQuery | ...` だった

**Comment by syuilo** [comment]
TypeScriptは`<T>`の型によって引数の型を変えるといったことはできないと思われる

**Comment by marihachi** [comment]
えーっ！？

**Comment by marihachi** [comment]
じゃあ無理ですねえ

**Comment by syuilo** [comment]
もうちょっと考えてみる

**Comment by marihachi** [comment]
すみません、ありがとうございます

**Comment by syuilo** [comment]
![image](https://user-images.githubusercontent.com/4439005/32412357-9c55d964-c238-11e7-8113-0ec01a63d337.png)

なんかできた

**Comment by marihachi** [comment]
やったー！

**Comment by syuilo** [comment]
3.1.0 で実装しました。
思っていた動作と合っているかご確認ください～

**Comment by marihachi** [comment]
ありがとうございますー！

**Comment by marihachi** [comment]
期待した動作をしましたー！感謝です
